### ISSUE TITLE
Similar workflow

### ISSUE THREAD

**Issue by jspaezp** [wfondrie/comet-mokapot-flashflq_example#1]
Hello there!

Just fyi:
I have a repo that does the mzml > comet > mokapot section of this workflow using snakemake.
https://github.com/jspaezp/open_speclib_workflow

I have never used flashlfq but I would love to add it.
LMK what you think.
Best,
Sebastian!

**Comment by wfondrie** [comment]
Thanks @jspaezp! I created this one just as an example for someone else learn from.

**Comment by jspaezp** [comment]
right on!
